module.exports = [
    {
        "firstName":"VenkataNarayana",
        "middleName":"KN",
        "lastName":"",
        "yob":"1948",
        "pin":"560019",
        "suburb":"HanumanthaNagara",
        "gothra":"Bhaaradvaaja",
        "veda":"Ruk",
        "education":"B.Com",
        "occupation":"business",
        "hobbies":"music",
        "maritalStatus":"married & continuing",
        "numOfSons":"2",
        "numOfDaughters":"1"
    },
    {
        "firstName":"Deepak",
        "middleName":"R",
        "lastName":"Sharma",
        "yob":"1969",
        "pin":"560010",
        "suburb":"RajajiNagara",
        "gothra":"Aathreyasa",
        "veda":"Ruk",
        "education":"BE",
        "occupation":"unemployed",
        "hobbies":"music",
        "maritalStatus":"not yet married",
        "numOfSons":"0",
        "numOfDaughters":"0"
    },
    {
        "firstName":"Gopal",
        "middleName":"N",
        "lastName":"Sharma",
        "yob":"1936",
        "pin":"560010",
        "suburb":"RajajiNagara",
        "gothra":"Bhaaradvaaja",
        "veda":"Yajus",
        "education":"diploma",
        "occupation":"pvt job",
        "hobbies":"cricket",
        "maritalStatus":"married & continuing",
        "numOfSons":"1",
        "numOfDaughters":"2"
    },
    {
        "firstName":"PrabhaShankar",
        "middleName":"",
        "lastName":"Nadig",
        "yob":"1959",
        "pin":"560010",
        "suburb":"RajajiNagara",
        "gothra":"Kaundinya",
        "veda":"Saama",
        "education":"BE",
        "occupation":"pvt job",
        "hobbies":"football",
        "maritalStatus":"married & continuing",
        "numOfSons":"1",
        "numOfDaughters":"1"
    },
    {
        "firstName":"Palani",
        "middleName":"",
        "lastName":"Goundar",
        "yob":"1977",
        "pin":"560040",
        "suburb":"VijayaNagara",
        "gothra":"Gauthama",
        "veda":"Ruk",
        "education":"BA",
        "occupation":"unemployed",
        "hobbies":"painting",
        "maritalStatus":"married but divorced",
        "numOfSons":"0",
        "numOfDaughters":"0"
    },
    {
        "firstName":"Ram",
        "middleName":"Krishnamurthy",
        "lastName":"Aanekere",
        "yob":"1959",
        "pin":"560040",
        "suburb":"VijayaNagara",
        "gothra":"Gauthama",
        "veda":"Ruk",
        "education":"B.Com",
        "occupation":"pvt job",
        "hobbies":"football",
        "maritalStatus":"married & continuing",
        "numOfSons":"1",
        "numOfDaughters":"1"
    },
    {
        "firstName":"AnanthaNarayana",
        "middleName":"S",
        "lastName":"Belakavaadi",
        "yob":"1928",
        "pin":"560003",
        "suburb":"Malleshvara",
        "gothra":"Aathreyasa",
        "veda":"Ruk",
        "education":"BA",
        "occupation":"pvt job",
        "hobbies":"cricket",
        "maritalStatus":"married & continuing",
        "numOfSons":"2",
        "numOfDaughters":"1"
    },
    {
        "firstName":"Puneeth",
        "middleName":"V",
        "lastName":"Nadig",
        "yob":"1985",
        "pin":"560010",
        "suburb":"RajajiNagara",
        "gothra":"Aathreyasa",
        "veda":"Ruk",
        "education":"BE",
        "occupation":"pvt job",
        "hobbies":"cricket",
        "maritalStatus":"married & continuing",
        "numOfSons":"1",
        "numOfDaughters":"0"
    },
    {
        "firstName":"Shreyamsa",
        "middleName":"B",
        "lastName":"Nadig",
        "yob":"1979",
        "pin":"560040",
        "suburb":"VijayaNagara",
        "gothra":"Gauthama",
        "veda":"Yajus",
        "education":"BSc",
        "occupation":"business",
        "hobbies":"meditation",
        "maritalStatus":"married & continuing",
        "numOfSons":"1",
        "numOfDaughters":"0"
    },
    {
        "firstName":"Vijay",
        "middleName":"",
        "lastName":"Nadig",
        "yob":"1956",
        "pin":"560010",
        "suburb":"RajajiNagara",
        "gothra":"Aathreyasa",
        "veda":"Ruk",
        "education":"BSc",
        "occupation":"pvt job",
        "hobbies":"cricket",
        "maritalStatus":"married & continuing",
        "numOfSons":"1",
        "numOfDaughters":"1"
    },
    {
        "firstName":"Vishva",
        "middleName":"",
        "lastName":"Nadig",
        "yob":"1966",
        "pin":"560010",
        "suburb":"RajajiNagara",
        "gothra":"Aathreyasa",
        "veda":"Ruk",
        "education":"diploma",
        "occupation":"govt job",
        "hobbies":"cricket",
        "maritalStatus":"married & continuing",
        "numOfSons":"2",
        "numOfDaughters":"0"
    },
    {
        "firstName":"Mahesh",
        "middleName":"",
        "lastName":"Nadig",
        "yob":"1999",
        "pin":"560019",
        "suburb":"HanumanthaNagara",
        "gothra":"Aathreyasa",
        "veda":"Ruk",
        "education":"B.Com",
        "occupation":"unemployed",
        "hobbies":"painting",
        "maritalStatus":"not yet married",
        "numOfSons":"0",
        "numOfDaughters":"0"
    },
    {
        "firstName":"Lakshmi Devi",
        "middleName":"",
        "lastName":"Nadig",
        "yob":"1988",
        "pin":"560019",
        "suburb":"HanumanthaNagara",
        "gothra":"Gauthama",
        "veda":"Saama",
        "education":"B.Com",
        "occupation":"pvt job",
        "hobbies":"painting",
        "maritalStatus":"not yet married",
        "numOfSons":"0",
        "numOfDaughters":"0"
    }
]